#!/bin/bash
cd src
make PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_ES2 USE_EXTERNAL_GLFW=TRUE USE_WAYLAND_DISPLAY=TRUE
cd ../examples
make PLATFORM=PLATFORM_DESKTOP GRAPHICS=GRAPHICS_API_OPENGL_ES2 USE_EXTERNAL_GLFW=TRUE USE_WAYLAND_DISPLAY=TRUE
